id = "gozer"
name = "Gozer"
version = "0.14.0"
schema_version = 1
authors = ["Jason Abbott"]
description = "Go template support with LSP (hover, diagnostics, go-to-definition)"
repository = "https://github.com/toba/gozer"

[language_servers.gozer]
name = "Gozer"
languages = ["Go Text Template", "Go HTML Template", "Go HTMX 2", "Go HTMX 4"]

[grammars.gotmpl]
repository = "https://github.com/toba/tree-sitter-go-template"
rev = "e8e1e41126552259406304462e2c5bba36a990d5"
