id = "gozer"
name = "Gozer"
version = "0.13.1"
schema_version = 1
authors = ["Jason Abbott"]
description = "Go template support with LSP (hover, diagnostics, go-to-definition)"
repository = "https://github.com/toba/gozer"

[language_servers.gozer]
name = "Gozer"
languages = ["Go Text Template", "Go HTML Template", "Go HTMX 2", "Go HTMX 4"]

[grammars.gotmpl]
repository = "https://github.com/toba/gozer"
path = "grammars/gotmpl"
